version: "3.9"

services:
  db:
    image: postgres:16
    container_name: desafio3-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: exemplo
    volumes:
      - pgdata-desafio3:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - desafio3-net

  cache:
    image: redis:7
    container_name: desafio3-redis
    ports:
      - "6379:6379"
    networks:
      - desafio3-net

  web:
    build: ./web
    container_name: desafio3-web
    ports:
      - "8083:8080"
    environment:
      DB_HOST: db
      DB_NAME: exemplo
      DB_USER: user
      DB_PASS: password
      REDIS_HOST: cache
      REDIS_PORT: 6379
    depends_on:
      - db
      - cache
    networks:
      - desafio3-net

networks:
  desafio3-net:
    driver: bridge

volumes:
  pgdata-desafio3: