version: "3.9"

services:
  service-a:
    build: ./service-a
    container_name: desafio4-service-a
    ports:
      - "5000:5000"
    networks:
      - desafio4-net

  service-b:
    build: ./service-b
    container_name: desafio4-service-b
    ports:
      - "5001:5001"
    environment:
      SERVICE_A_URL: http://service-a:5000
    depends_on:
      - service-a
    networks:
      - desafio4-net

networks:
  desafio4-net:
    driver: bridge