version: "3.9"

services:
  db:
    image: postgres:16
    container_name: desafio2-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: exemplo
    ports:
      - "5432:5432"
    volumes:
      - pgdata-desafio2:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata-desafio2: